export default {
  GET_SINGLE_TAG: 'GET_SINGLE_TAG',
  GET_MEDIA_OF_SINGLE_TAG: 'GET_MEDIA_OF_SINGLE_TAG',
  GET_SINGLE_MEDIA: 'GET_SINGLE_MEDIA',
  GET_MEDIA_OF_SINGLE_USER: 'GET_MEDIA_OF_SINGLE_USER',
  SET_PREVIOUS_TAG: 'SET_PREVIOUS_TAG',
  GET_RELATED_TAGS: 'GET_RELATED_TAGS',
};
